import type { Metadata } from "next";
import { Rubik, Merriweather } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/layout/Header"

const rubik = Rubik({
  variable: "--font-text",
  subsets: ["latin"],
  display: 'swap',
});
const merriweather = Merriweather({
  variable: "--font-style",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"] as Array<"300" | "400" | "700" | "900">,
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Lawfirm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${merriweather.variable} font-text antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
